### ISSUE TITLE
pydriosm Import fails due to "ModuleNotFoundError: No module named 'pyhelpers.dir'"

### ISSUE THREAD

**Issue by DBlev886** [mikeqfu/pydriosm#27]
As the title says, I tried to install pydriosm via "pip install --upgrade git+https://github.com/mikeqfu/pydriosm.git" without success as it returned an "ModuleNotFoundError: No module named 'pyhelpers.dir'". 
Installation via "pip install --upgrade pydriosm" works but I can't import afterwards since it also gives me an "ModuleNotFoundError: No module named 'pyhelpers.dir'". 
I uninstalled and reinstalled pyhelpers and pydriosm but it didn't fix the problem. 
I'm working with Windows 11 and Python 3.10. Any idea how to fix this?

**Comment by zzx1505815205** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，您的邮件我已收到，祝好！                                       张召星

**Comment by mikeqfu** [comment]
The reasons for the issues @DBlev886 raised are: 

> _install pydriosm via "pip install --upgrade git+https://github.com/mikeqfu/pydriosm.git" without success_

**This is due to a major change to `pydriosm` is in progress. A new version of `pydriosm` will be released soon. Currently, `pip install pydriosm` should work.** 

> _Installation via "pip install --upgrade pydriosm" works but I can't import afterwards since it also gives me an "ModuleNotFoundError: No module named 'pyhelpers.dir'"_

**This is due to the recent update in the dependency [pyhelpers](https://github.com/mikeqfu/pyhelpers), in which the module `dir` has been renamed to `dirs`.** 

As `pydrioms==2.0.3` has been installed, a temporary solution to the above issues is to downgrade [pyhelpers](https://github.com/mikeqfu/pyhelpers) to an earlier version (e.g. pyhelpers==1.3.4). Can you try `pip install pyhelpers==1.3.4` first, and then `import pydriosm`?

**Comment by DBlev886** [comment]
Hey Mike, 
Thanks for your quick response. 
I downgraded pyhelpers but importing pydriosm returns an "ImportError: cannot import name 'validate_input_data_dir' from 'pyhelpers.dir' (c:\Users\........\lib\site-packages\pyhelpers\dir.py)" now

**Comment by mikeqfu** [comment]
Hi @DBlev886, I tried to reproduce the issues. Hopefully the following way could work around the issues with the current version. Can you please try:

- `pip install python-rapidjson pyhelpers==1.2.18`

In this way, `import pydriosm` should work properly. :slightly_smiling_face:

You might see a `UserWarning` about `python-Levenshtein` when importing pydriosm. It doesn't indicate that there is an error and the warning message will disappear after `python-Levenshtein` is installed. To remove the warning, you could try `pip install python-Levenshtein`, or install its .whl file (downloadable from https://www.lfd.uci.edu/~gohlke/pythonlibs/#python-levenshtein) instead.

**Comment by DBlev886** [comment]
Hey Mike, 
unfortunately, it still shows the same error. I tried to downgrade pyhelpers until 1.2.15, but the problem remains. 
Can you reveal when the new pydriosm version will be released? Maybe I can wait and hope that the new version works for me.

**Comment by mikeqfu** [comment]
Hi @DBlev886, 

Was it the "same error" as you mentioned in your previous comment:

> "ImportError: cannot import name 'validate_input_data_dir' from 'pyhelpers.dir' ...

That doesn't sound right, because the function [validate_input_data_dir()](https://github.com/mikeqfu/pyhelpers/commit/ff821197e1e5bedda1893e63a0985c15c6eea6eb#diff-9658546df62eded721ef6049c33f4b2d7e985d9cce8c08ba9538a32da5229a09L245) was included in pyhelpers<=1.2.18, but was later renamed to [validate_dir()](https://github.com/mikeqfu/pyhelpers/commit/ff821197e1e5bedda1893e63a0985c15c6eea6eb#diff-9658546df62eded721ef6049c33f4b2d7e985d9cce8c08ba9538a32da5229a09R245) which caused the error.

I have just tried to reproduce the issues again in an empty virtual environment for both Python 3.9 and 3.10. With the installation of both `pyhelpers==1.2.18` and `pydriosm` by running the following command:

- `pip install pyhelpers==1.2.18 python-rapidjson "GDAL-3.4.3-cp310-cp310-win_amd64.whl" pydriosm` 

I didn't have any issues with `import pydriosm`.

**Comment by DBlev886** [comment]
Maybe I did something wrong. I just tried again and it's working now. Thanks a lot for your help!

**Comment by zzx1505815205** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，您的邮件我已收到，祝好！                                       张召星
